/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baseDeDonnées;

/**
 *
 * @author Farid M.H
 */
public class Principale extends javax.swing.JFrame {

    /**
     * Creates new form Principale
     */
    public Principale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bouton_lecteur = new javax.swing.JButton();
        bouton_emprunt = new javax.swing.JButton();
        bouton_livre = new javax.swing.JButton();
        bouton_fermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Application du Gestion d'une Bibliothèque");

        bouton_lecteur.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        bouton_lecteur.setText("GESTION DES LECTEURS");

        bouton_emprunt.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        bouton_emprunt.setText("GESTION DES EMPRUNTS");
        bouton_emprunt.setToolTipText("");
        bouton_emprunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_empruntActionPerformed(evt);
            }
        });

        bouton_livre.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        bouton_livre.setText("GESTION DES LIVRES");
        bouton_livre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_livreActionPerformed(evt);
            }
        });

        bouton_fermer.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        bouton_fermer.setText("FERMER");
        bouton_fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_fermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bouton_lecteur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bouton_emprunt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bouton_livre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bouton_fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bouton_lecteur)
                .addGap(40, 40, 40)
                .addComponent(bouton_emprunt)
                .addGap(38, 38, 38)
                .addComponent(bouton_livre)
                .addGap(42, 42, 42)
                .addComponent(bouton_fermer)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(556, 418));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_empruntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_empruntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_empruntActionPerformed

    private void bouton_livreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_livreActionPerformed
        Livre l = new Livre();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_bouton_livreActionPerformed

    private void bouton_fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_fermerActionPerformed
        dispose();
    }//GEN-LAST:event_bouton_fermerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_emprunt;
    private javax.swing.JButton bouton_fermer;
    private javax.swing.JButton bouton_lecteur;
    private javax.swing.JButton bouton_livre;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
